-- require("noice").setup({
--     views = {
--       cmdline_popup = {
--         border = {
--           style = "rounded",
--         },
--         filter_options = {},
--         win_options = {
--           winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder",
--         },
--       },
--     },
--   })
